[package]

name = "chipmunk-sys"
version = "0.0.1"
authors = ["Ty Overby <ty@pre-alpha.com>"]

build = "build.rs"

lib = "chipmunk_sys"

[build-dependencies]
gcc = "*"

#[build-dependencies.rust-bindgen]
#git = "git@github.com:crabtw/rust-bindgen.git"
